### ISSUE TITLE
SNOW-1922932: pandas/_libs/window/aggregations.cpp:799:10: fatal error: 'ios' file not found

### ISSUE THREAD

**Issue by sfc-gh-wjaskowski** [snowflakedb/snowflake-ml-python#140]
`pip install snowflake-ml-python`

results in

(...)
```      
creating build/temp.macosx-11.1-arm64-cpython-312/pandas/_libs/window
      clang++ -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Users/wjaskowski/miniconda3/envs/migrations/include -arch arm64 -fPIC -O2 -isystem /Users/wjaskowski/miniconda3/envs/migrations/include -arch arm64 -DNPY_NO_DEPRECATED_API=0 -Ipandas/_libs/window -I/private/var/folders/bq/z6ctcbxs43l47x0hfm6538rh0000gn/T/pip-build-env-xamzd0dm/overlay/lib/python3.12/site-packages/numpy/core/include -I/Users/wjaskowski/miniconda3/envs/migrations/include/python3.12 -c pandas/_libs/window/aggregations.cpp -o build/temp.macosx-11.1-arm64-cpython-312/pandas/_libs/window/aggregations.o -Wno-error=unreachable-code
      pandas/_libs/window/aggregations.cpp:799:10: fatal error: 'ios' file not found
        799 | #include "ios"
            |          ^~~~~
      1 error generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pandas)
```

macos 15.3

**Comment by sfc-gh-thoyt** [comment]
Thanks for reporting. It appears that you're trying to install snowflake-ml-python into a Python 3.12 environment. We don't yet support Python 3.12. It's possible that you'd run into the same issue with another version of python.

 In case you don't have these headers installed, could you run `xcode-select --install` and try again with python 3.9-11?

**Comment by sfc-gh-wjaskowski** [comment]
It works fine with 3.11. Thanks!
